spring:
  data:
    mongodb:
      host:
      database:
      port:
      username:
      password:
      authentication-database:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
lws:
  gatewayAddress: